name: 'Screenshot Test'
description: 'Runs Paparazzi/Roborazzi verify task and uploads failure diffs as artifacts'

inputs:
  screenshot-task:
    description: 'Gradle task for screenshot verification (e.g. :app:verifyPaparazziDebug)'
    required: true
  working-directory:
    description: 'Working directory for Gradle commands'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Run screenshot verification
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ./gradlew ${{ inputs.screenshot-task }} --no-daemon

    - name: Upload screenshot failures
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: screenshot-failures
        path: |
          **/build/paparazzi/failures/
          **/build/outputs/roborazzi/
